### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by asygamesperson** [ChanceSD/PvPManager-Issues#192] opened 2024-10-10 16:55 UTC
**Describe the bug**

**To Reproduce**
I get this error in console: https://paste.helpch.at/egowitihow.rb

**Expected behavior**

**Plugin and Server version**
Use '/ver PvPManager' and '/ver' to get both versions
[19:55:20 INFO]: PvPManager version 3.34.33
[19:55:20 INFO]: A powerful plugin to manage various PvP combat features
[19:55:20 INFO]: Website: https://www.spigotmc.org/resources/pvpmanager.10610/
[19:55:20 INFO]: Author: ChanceSD
**Screenshots**

**Additional context**

**Comment by ChanceSD** [comment] 2024-10-10 18:06
Did it cause any issue? Should be an harmless error but will be fixed. 
Run a /pmr reload if there is any issue

**Comment by asygamesperson** [comment] 2024-10-10 18:26
I get this error now: https://paste.helpch.at/atexaqutum.php

**Comment by ChanceSD** [comment] 2024-10-13 20:15
Sorry for the delay, there's probably some error before that would be the cause of the issue, because I can't tell the issue based on those errors. Is it still happening or did it improve after a server restart?

If it's still happening, can you share the entire server log? Use https://mclo.gs/ to paste it if you want

**Comment by ChanceSD** [comment] 2024-12-30 00:54
Closing for inactivity and might have been fixed, since I haven't seen any similar issue from other users.

**Closed as completed by ChanceSD** 2024-12-30 00:54 UTC
Labels: bug
